spring:
  application:
    name: SpringSecurityApp
  # Database Information
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3307/securitydb
  #Security Information
  security:
    user:
      name: alan
      password: alan1234
