spring:
  application:
    name: CrudSpringSecurity
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3307/spring_crud_secure
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver